replicaCount: 2

image:
  repository: researchradar
  pullPolicy: Never
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: "nginx"
  host: researchradar.local
  annotations: {}

env:
  GROQ_API_KEY: "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"
  SECRET_KEY: "dev-secret-key-researchradar-2026"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
