apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: researchradar-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: researchradar.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: researchradar-svc
                port:
                  number: 80