apiVersion: v1
kind: Secret
metadata:
  name: {{ include "researchradar.fullname" . }}-secrets
  labels:
    app: {{ include "researchradar.fullname" . }}
type: Opaque
stringData:
  GROQ_API_KEY: {{ .Values.env.GROQ_API_KEY | quote }}
