apiVersion: v1
kind: Service
metadata:
  name: {{ include "researchradar.fullname" . }}-svc
  labels:
    app: {{ include "researchradar.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ include "researchradar.fullname" . }}
